### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by Brancovanbeek** [Ravirkt/fix-the-flow-interactive-website#10]
het is wel duidelijk eigenlijk hij gebruikt iconen om het duidelijk te maken dat je ergens naar toe kan (feed forward).  er mist alleen wel (feedback) dat er een bestand is verzonden om een playlist te maken. misschien is het handig om pijltjes te zetten om te navigeren. en een knop om naar het begin te gaan want nu is er alleen een knop om naar het eind te gaan.

**Comment by Ravirkt** [comment]
bedankt voor de feedback. form feedback solve: https://github.com/Ravirkt/fix-the-flow-interactive-website/commit/2e0e76337eb132b1ccb701e6db742b2fdcbb6476
