### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by Saif8599** [Ravirkt/fix-the-flow-interactive-website#11]
Feedforward :
De interface maakt gebruik van iconen om duidelijk aan te geven waar je naartoe kunt navigeren. 

Feedback : 
Echter ontbreekt feedback om de gebruiker te laten weten dat een bestand succesvol is verzonden voor het maken van een playlist. 

Tips : 
Het toevoegen van navigatiepijlen zou handig kunnen zijn om de gebruikerservaring te verbeteren, zodat hij/zij gemakkelijker kan navigeren. Daarnaast zou een knop om terug naar het begin te gaan een waardevolle toevoeging zijn, aangezien er momenteel alleen een knop is om naar het einde te navigeren. Ook vind ik het prettiger om de playlist titel boven aan te zetten.

**Comment by Ravirkt** [comment]
bedankt voor de feedback, feedback voor form commit: https://github.com/Ravirkt/fix-the-flow-interactive-website/commit/2e0e76337eb132b1ccb701e6db742b2fdcbb6476
