### ISSUE TITLE
Code review (user interaction)

### ISSUE THREAD

**Issue by kimnikitaschijf** [Ravirkt/fix-the-flow-interactive-website#8]
- Goed gebruik gemaakt van comments waarin je uitlegt wat er gebeurd in dit stukje code. 
- Je gebruikt `document.getElementById`. Dit kan je als een variabele schrijven en daarna kan je met die variabele verder werken, zodat je code netjes en overzichtelijk blijft. 
- Je gebruikt duidelijke namen bij de variabelen die je nu al hebt. Je gebruikt alleen nog niet genoeg variabelen. 
- Je kan in je CSS `scroll-behavior: smooth` aanzetten. Dit hoeft niet in je JS.  https://github.com/Ravirkt/fix-the-flow-interactive-website/blob/cb30a5ca30676f0f975f549d676ef6ce0069c8f9/javascript/lessons.js#L65
- Je hebt HTML geschreven in je JS staan. Dit kan je beter in je HTML zetten, zodat je geen complicaties gaat krijgen. Met CSS kan je het weghalen met `display: none`. In JS hoef je dan alleen de class met `display: none` van het element weg te halen, zodat het wel te zien is. 
- Je hebt uitgecommende HTML in je JS staan. Als je dit niet gebruikt kun je dit beter weghalen. Dit maakt het minder verwarrend. 😌

@ambersr @vsheo @lemuelmgsn

**Comment by Ravirkt** [comment]
bedankt voor de feedback! link naar commit scroll: https://github.com/Ravirkt/fix-the-flow-interactive-website/commit/6ca7aced7d8494a445d49ea8161f65b41c1ecc26
