### ISSUE TITLE
Design review (user interaction)

### ISSUE THREAD

**Issue by kimnikitaschijf** [Ravirkt/fix-the-flow-interactive-website#9]
**Feedforward:**
- De play-knop bij de playlist kaarten geven goed aan bij de gebruiker dat zij hier iets kunnen laten afspelen. De knoppen hebben een `hover` wat het duidelijk maakt dat deze knoppen klikbaar zijn. 
- Het plus icoontje bij de 'make a playlist' geeft aan dat de gebruiker hier iets kan toevoegen. Als je hier een `hover` aan zou toevoegen zou dit nog duidelijker zijn. Zodra je op de plus klikt wordt het voor de gebruiker onduidelijk wat zij verder kunnen doen. 
- De icoontjes op de kaarten zelf (download, toevoegen etc.) hebben ook een `hover`. Dit is duidelijk voor de gebruiker dat hier een interactie op zit. Goed bezig! 
- Bij het plus icoontje heb je eronder tekst gezet waarin je uitlegt wat de plus knop doet. Dit is heel duidelijk! 

**Feedback:**
- Je hebt nog niet duidelijk genoeg feedback toegepast. Als je bv op een kaartje klikt, dat er als gevolg van die interactie een kleine animatie komt. Dit zou je nog meer kunnen toepassen. 

**Algemene feedback over design:** 
- De witte achtergrond bij het 'plus' knopje zou je kunnen weghalen, zodat het meer als 1 geheel wordt gezien. 
- Mooi design wat overzichtelijk is voor de gebruiker. 
- Goed responsive gewerkt. Ziet er goed uit! 

@ambersr @vsheo @lemuelmgsn

**Comment by Ravirkt** [comment]
feedback verwerkt in commit https://github.com/fdnd-task/fix-the-flow-interactive-website/commit/b79d341d5d08a7831826c8cc1e14ced088bdb0ac
